language: cpp
compiler: gcc
dist: trusty

# Boost
addons: 
  apt: 
    packages: libboost-all-dev

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint

install: 
  # C++14
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  # Codecov
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-6 90
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # valgrind, for helgrind and memcheck
  - sudo apt-get install -qq valgrind
  # SLOCcount
  - sudo apt-get install sloccount
  # proselint
  - sudo pip install proselint

script: 
  # Build and run the tests
  - qmake boost_units_example_6.pro
  - make debug
  - ./boost_units_example_6
  # helgrind
  - valgrind --tool=helgrind --log-file=helgrind.log -v ./boost_units_example_6
  - cat helgrind.log
  # memcheck
  - valgrind --leak-check=full -v --show-reachable=yes --log-file=memcheck.log ./boost_units_example_6
  - cat memcheck.log
  # Build and run and profile normal program
  - qmake boost_units_example_6.pro
  - make release
  - time ./boost_units_example_6
  - gprof boost_units_example_6 > gprof.log
  - head gprof.log
  # Get code coverage
  - ./get_code_cov
  - codecov
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . 
  # Call OCLint
  - ./do_oclint
  # Get my folder
  - my_github=${PWD##*/}  
  # SLOCcount
  - cd ..; sloccount --overhead 1 --personcost 22614 $my_github; cd $my_github
  # proselint
  - proselint README.md

after_success:
  # Codecov
  - bash <(curl -s https://codecov.io/bash)
